// =============================================================================
// 会議要約から案件(deals)を自動作成するロジック (PhaseD)
//
// 発動条件(全て AND):
//   1) AI が suggestedDealTitle を生成した
//   2) meeting.contact_id が紐付いている(PhaseC で自動 or 手動で設定済)
//   3) meeting.deal_id がまだ無い(二重作成防止)
//   4) suggestedDealTitle が品質ゲート(空文字/極端短/汎用語のみ NG)を通過
//
// 重複検出:
//   - 同じ contact_id × 正規化済 title が既存にあれば既存 deal に紐付け
//   - 無ければ新規作成(phase=proposal_planned)
//
// この TS は **純粋ロジック** に絞り、DB 操作は呼び出し側で行う(テスト容易性)。
// 実装は netlify/functions/summarize-meeting-background.js に inline + ここに同期実装。
// =============================================================================

export interface AutoCreateDealInput {
  /** AI が生成した案件名候補 */
  suggestedDealTitle: string | null | undefined;
  /** meeting.contact_id が設定されているか */
  meetingHasContact: boolean;
  /** meeting.deal_id が既に設定されているか */
  meetingHasDeal: boolean;
}

export type AutoCreateDecision =
  | { create: true; cleanedTitle: string }
  | { create: false; reason: 'no_title' | 'no_contact' | 'already_has_deal' | 'title_too_short' | 'title_generic' };

// 共有定数(BG function とも同期、`auto-create-deal-config.json` が真実源)
import config from './auto-create-deal-config.json';
const MIN_TITLE_LENGTH = config.minTitleLength;
const GENERIC_TITLES = new Set<string>(config.genericTitles.map((s) => s.toLowerCase()));

export const AUTO_GENERATED_NOTE_PREFIX = config.autoGeneratedNotePrefix;
export const AUTO_GENERATED_SOURCE = config.autoGeneratedSource;

/**
 * 案件自動作成すべきか判定する。
 * 副作用なし、テスト容易。
 */
export function shouldAutoCreateDeal(input: AutoCreateDealInput): AutoCreateDecision {
  if (!input.suggestedDealTitle || input.suggestedDealTitle.trim().length === 0) {
    return { create: false, reason: 'no_title' };
  }
  if (!input.meetingHasContact) {
    return { create: false, reason: 'no_contact' };
  }
  if (input.meetingHasDeal) {
    return { create: false, reason: 'already_has_deal' };
  }
  const cleaned = input.suggestedDealTitle.trim().replace(/\s+/g, ' ');
  if (cleaned.length < MIN_TITLE_LENGTH) {
    return { create: false, reason: 'title_too_short' };
  }
  if (GENERIC_TITLES.has(cleaned.toLowerCase())) {
    return { create: false, reason: 'title_generic' };
  }
  return { create: true, cleanedTitle: cleaned };
}

/**
 * 重複判定用にタイトルを正規化(空白統一+小文字化)。
 * 既存 deals.title の正規化済値と === 比較で使う。
 */
export function normalizeDealTitle(s: string): string {
  return s.trim().replace(/\s+/g, ' ').toLowerCase();
}

/**
 * 2つのタイトルが「事実上同じ案件名」か判定。
 * 正規化済の完全一致で判定(includes による誤検出を避ける)。
 */
export function isSameDealTitle(a: string, b: string): boolean {
  return normalizeDealTitle(a) === normalizeDealTitle(b);
}
